# Generated by Django 5.2 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_item_uploaded_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "normalized_name",
                    models.CharField(editable=False, max_length=100),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("normalized_name",),
                        name="unique_provider_genre_normalized_name",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="provider_genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="items",
                to="app.providergenre",
            ),
        ),
    ]
